"""add count redirect

Revision ID: 05765d4be385
Revises: c5c4576a9dac
Create Date: 2026-03-04 17:21:58.019307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "05765d4be385"
down_revision: Union[str, Sequence[str], None] = "c5c4576a9dac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Links",
        sa.Column(
            "count_redirects",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Links", "count_redirects")
    # ### end Alembic commands ###
